update redis to timeseries
Nouuu/microservice-payment pull request #6
Opened 2022-06-02 18:25 UTC by SwannHERRERA

2022-06-02 18:47 UTC, Nouuu requested changes
Modifier le docker-compose pour prendre la nouvelle variable d'environnement
Bye bye le hset 😿

2022-06-02 18:47 UTC, Nouuu commented on boissipay/src/main/java/org/esgi/RedisConfiguration.java
> +    private static long redisTll = 60 * 60 * 24;
Valeur static ? Par défaut ?
Tu as testé ça avec le `application.properties` si ça ne faisait pas nimp ?

2022-06-02 18:47 UTC, Nouuu commented on boissipay/src/main/java/org/esgi/SpringPaymentApiDelegate.java
> +                );
On abandonne le dictionnaire du coup ? 🥲

2022-06-06 15:40 UTC, SwannHERRERA commented on boissipay/src/main/java/org/esgi/RedisConfiguration.java
> +    private static long redisTll = 60 * 60 * 24;
le problème c'est que si jamais c'est pas static il faut que je le prenne en propriété dans ma classe le RedisConfiguration et c'est pas le but du coup je préfère le prendre en static et je peux pas prendre de application properties dans le static

2022-06-06 15:40 UTC, SwannHERRERA commented on boissipay/src/main/java/org/esgi/SpringPaymentApiDelegate.java
> +                );
ça reste un dictionnaire

2022-06-07 10:22 UTC, Nouuu commented on boissipay/src/main/java/org/esgi/RedisConfiguration.java
> +    private static long redisTll = 60 * 60 * 24;
Pas compris ce que tu fais avec le setter dessus alors, parce que le foncitonnement spring va l'utiliser pour le set depuis le fichiers application.properties

2022-06-07 10:23 UTC, Nouuu commented on boissipay/src/main/java/org/esgi/SpringPaymentApiDelegate.java
> +                );
C'est juste du clé : valeurs en fait
Mais plus vraiment un dictionnaire

2023-02-11 00:08 UTC, closed without merging

2023-02-11 22:33 UTC, Nouuu commented
WTF xD